import './global.css';
import { ModeToggle, ThemeProvider } from '@jsfront/components';
import { Navigation } from '@jsfront/components';

export const metadata = {
  title: 'Welcome to dashboard',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <nav className="sticky top-0 z-50 w-full bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60 p-4 flex justify-between shadow-md border-b">
            <Navigation
              items={[
                { label: 'Overview', href: '/', exact: true },
                { label: 'Posts', href: '/posts' },
              ]}
            />
            <ModeToggle />
          </nav>
          <div className="container p-4">{children}</div>
        </ThemeProvider>
      </body>
    </html>
  );
}
